#	$NetBSD: Makefile,v 1.6 2009/04/14 22:15:17 lukem Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

.if defined(__MINIX)
.include "../minix-config.inc"
.endif

PROG=	basename
MLINKS=	basename.1 dirname.1

.include <bsd.prog.mk>
