#	$NetBSD: Makefile,v 1.10 2009/04/14 22:15:25 lukem Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

.if defined(__MINIX)
.include "../minix-config.inc"
.endif

PROG=	printf

.include <bsd.prog.mk>
